# Generated by Django 3.2.10 on 2023-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_filter',
            field=models.CharField(choices=[('Life', 'Life'), ('Technology', 'Technology'), ('Advice', 'Advice'), ('Love', 'Love'), ('Work', 'Work')], default='Life', max_length=32),
        ),
    ]
